/**
 * cubeai 引擎适配器 —— STM32Cube.AI(STM32 官方推理工具链)。
 * 阶段 2 定位:占位实现(契约验证 + 矩阵可替换);真实 stedgeai 转换在阶段 3 接入。
 * requires: stedgeai(STM32Cube.AI CLI),不可用时 registry 标记不可用,规划期报错。
 */

/**
 * @returns {import('../../contracts/engine-contract').EngineAdapter & { requires: string[] }}
 */
function createCubeaiEngine() {
  return {
    id: 'cubeai',
    requires: ['stedgeai'],

    capabilities() {
      return {
        id: 'cubeai',
        version: '0.1.0',
        inputFormats: ['onnx', 'tflite'],
        outputFormats: ['c-graph'],
        quantSchemes: ['int8', 'fp32'],
        ops: ['CONV_2D', 'DEPTHWISE_CONV_2D', 'FULLY_CONNECTED', 'SOFTMAX'],
        compatibleTargets: ['host', 'qemu-stm32f4', 'board-stm32f4']
      };
    },

    async convert({ artifact, target }) {
      return {
        kind: 'converted-model',
        content: JSON.stringify({
          engine: 'cubeai',
          op: 'convert',
          from: artifact.id,
          target: target.id,
          format: 'c-graph',
          note: '阶段 2 占位:真实 stedgeai 转换待阶段 3'
        })
      };
    },

    async quantize({ artifact, dataset, scheme }) {
      return {
        kind: 'quantized-model',
        content: JSON.stringify({
          engine: 'cubeai',
          op: 'quantize',
          from: artifact.id,
          dataset: dataset ? dataset.id : undefined,
          scheme,
          activationBits: 8,
          weightBits: 8
        })
      };
    },

    async generateCode({ artifact, config }) {
      return {
        kind: 'generated-code',
        content: `/* generated by mcu-ai-harness cubeai engine (phase-2 placeholder) */
/* source artifact: ${artifact.id} | outputDir: ${config.outputDir} */
#include "network.h"
#include "network_data.h"
`
      };
    },

    async run() {
      return { ok: true, outputs: { label: 'unknown', confidence: 0.8 } };
    },

    async evaluate({ bundle, target, dataset }) {
      return {
        kind: 'eval-report',
        content: JSON.stringify({
          engine: 'cubeai',
          target: target.capabilities().id,
          dataset: dataset.id,
          model: bundle.id,
          accuracy: 0.93,
          latencyMs: 18.2,
          ramBytes: 6144,
          flashBytes: 12288
        })
      };
    }
  };
}

module.exports = { createCubeaiEngine };
