/**
 * espdl 引擎适配器 —— ESP-DL(乐鑫 ESP32 系深度学习库)。
 * 阶段 2 定位:占位实现(矩阵可替换);真实 esp-dl 模型转换待阶段 3。
 * requires: idf.py(ESP-IDF 工具链)。
 */

/**
 * @returns {import('../../contracts/engine-contract').EngineAdapter & { requires: string[] }}
 */
function createEspdlEngine() {
  return {
    id: 'espdl',
    requires: ['idf.py'],

    capabilities() {
      return {
        id: 'espdl',
        version: '0.1.0',
        inputFormats: ['onnx'],
        outputFormats: ['cpp'],
        quantSchemes: ['int8', 'fp32'],
        ops: ['CONV_2D', 'DEPTHWISE_CONV_2D', 'FULLY_CONNECTED'],
        compatibleTargets: ['host', 'board-esp32']
      };
    },

    async convert({ artifact, target }) {
      return {
        kind: 'converted-model',
        content: JSON.stringify({
          engine: 'espdl',
          op: 'convert',
          from: artifact.id,
          target: target.id,
          format: 'cpp',
          note: '阶段 2 占位:真实 esp-dl 转换待阶段 3'
        })
      };
    },

    async quantize({ artifact, dataset, scheme }) {
      return {
        kind: 'quantized-model',
        content: JSON.stringify({
          engine: 'espdl',
          op: 'quantize',
          from: artifact.id,
          dataset: dataset ? dataset.id : undefined,
          scheme,
          channelwise: true
        })
      };
    },

    async generateCode({ artifact, config }) {
      return {
        kind: 'generated-code',
        content: `/* generated by mcu-ai-harness espdl engine (phase-2 placeholder) */
/* source artifact: ${artifact.id} | outputDir: ${config.outputDir} */
#include "model.hpp"
static const int8_t model_data[] = { 0, 1, 2, 3 };
`
      };
    },

    async run() {
      return { ok: true, outputs: { label: 'unknown', confidence: 0.85 } };
    }
  };
}

module.exports = { createEspdlEngine };
