/**
 * tflm 引擎适配器 —— 阶段 1 首个引擎(ADR H12,用于验证 EngineContract)。
 * MVP 定位:转换/量化/生成/评测均为占位实现,证明契约可落地;
 * 真实 tflite→c 转换与推理在阶段 2/3 接入(适配器边界不变,只换实现)。
 * 无状态:方法返回 ArtifactPayload,由 stage 落盘(保证血缘/runId 完整)。
 */

/**
 * @returns {import('../../contracts/engine-contract').EngineAdapter}
 */
function createTflmEngine() {
  return {
    id: 'tflm',

    capabilities() {
      return {
        id: 'tflm',
        version: '0.1.0',
        inputFormats: ['tflite'],
        outputFormats: ['c-array'],
        quantSchemes: ['int8'],
        ops: ['CONV_2D', 'DEPTHWISE_CONV_2D', 'FULLY_CONNECTED'],
        compatibleTargets: ['host']
      };
    },

    async convert({ artifact, target }) {
      return {
        kind: 'converted-model',
        content: JSON.stringify({
          engine: 'tflm',
          op: 'convert',
          from: artifact.id,
          target: target.id,
          format: 'c-array',
          note: 'MVP: 占位转换,真实 tflite→c 待阶段 2 接入'
        })
      };
    },

    async quantize({ artifact, dataset, scheme }) {
      return {
        kind: 'quantized-model',
        content: JSON.stringify({
          engine: 'tflm',
          op: 'quantize',
          from: artifact.id,
          dataset: dataset ? dataset.id : undefined,
          scheme,
          scale: 0.0078125,
          zeroPoint: 128
        })
      };
    },

    async generateCode({ artifact, config }) {
      return {
        kind: 'generated-code',
        content: `/* generated by mcu-ai-harness tflm engine (MVP placeholder) */
/* source artifact: ${artifact.id} | outputDir: ${config.outputDir} */
#include "model_data.h"
const unsigned char model_data[] = { 0x1f, 0x8b, 0x00, 0x00 };
const unsigned int model_data_len = 4;
`
      };
    },

    async run() {
      return { ok: true, outputs: { label: 'unknown', confidence: 0.9 } };
    },

    async evaluate({ bundle, target, dataset }) {
      // MVP: 模拟评测;阶段 3 接入真实精度/延迟/内存测量
      return {
        kind: 'eval-report',
        content: JSON.stringify({
          engine: 'tflm',
          target: target.capabilities().id,
          dataset: dataset.id,
          model: bundle.id,
          accuracy: 0.95,
          latencyMs: 12.5,
          ramBytes: 4096,
          flashBytes: 8192
        })
      };
    }
  };
}

module.exports = { createTflmEngine };
