/**
 * 第三方引擎示例(D5-5:验证贡献规范可用)——模拟"厂商 Y"的推理引擎。
 * 完整接入流程见 docs/embedded-ai-harness-contributing.md:
 *   1. 开发(本文件)
 *   2. 校验: node scripts/validate-harness-adapter.js --kind engine harness/examples/my-engine
 *   3. 注册: createDefaultRegistry().registerEngine(require('my-engine')())
 *   4. 使用: pipeline.stages[].engine = 'my-engine'
 */

/**
 * @returns {import('../../lib/contracts/engine-contract').EngineAdapter & { requires: string[] }}
 */
function createMyEngine() {
  return {
    id: 'my-engine',
    requires: [],

    capabilities() {
      return {
        id: 'my-engine',
        version: '1.0.0',
        inputFormats: ['onnx', 'tflite'],
        outputFormats: ['c-array'],
        quantSchemes: ['int8', 'fp32'],
        ops: ['CONV_2D', 'DEPTHWISE_CONV_2D', 'FULLY_CONNECTED', 'SOFTMAX'],
        compatibleTargets: ['host']
      };
    },

    async convert({ artifact, target }) {
      return {
        kind: 'converted-model',
        content: JSON.stringify({ engine: 'my-engine', op: 'convert', from: artifact.id, target: target.id, note: '第三方引擎示例' })
      };
    },

    async quantize({ artifact, dataset, scheme }) {
      return {
        kind: 'quantized-model',
        content: JSON.stringify({ engine: 'my-engine', op: 'quantize', from: artifact.id, scheme, vendor: 'Y' })
      };
    },

    async generateCode({ artifact, config }) {
      return {
        kind: 'generated-code',
        content: `/* generated by my-engine (vendor Y) | source: ${artifact.id} */\n#include "y_model.h"\n`
      };
    },

    async run() {
      return { ok: true, outputs: { label: 'unknown', confidence: 0.9 } };
    }
  };
}

module.exports = { createMyEngine };
