/**
 * 引擎适配器模板 —— 复制本文件到你的适配器目录(如 adapters/engine/my-engine/index.js),
 * 按注释替换实现。校验:node scripts/validate-harness-adapter.js --kind engine <路径>
 * 契约见 docs/embedded-ai-harness-contributing.md 与 harness/lib/contracts/engine-contract.ts。
 */

/**
 * 引擎工厂 —— 必须导出(名称 create*Engine)。
 * 无状态:方法返回 ArtifactPayload({ kind, content, labels? }),由 stage 落盘保证血缘完整。
 * @returns {import('../../../contracts/engine-contract').EngineAdapter & { requires: string[] }}
 */
function createTemplateEngine() {
  return {
    /** 唯一 id:planner/registry 按此引用(如 pipeline.stages[].engine) */
    id: 'template-engine',

    /** 工具链依赖声明(可选):缺失时 registry 标记不可用,规划期报 not available */
    requires: [],

    /** 能力声明 —— 规划期静态校验依据 */
    capabilities() {
      return {
        id: 'template-engine',
        version: '0.1.0',
        inputFormats: ['onnx'],
        outputFormats: ['c-array'],
        quantSchemes: ['int8'],
        ops: ['CONV_2D'],
        compatibleTargets: ['host']
      };
    },

    /** 模型导入与转换 → converted-model payload */
    async convert({ artifact, target }) {
      return {
        kind: 'converted-model',
        content: JSON.stringify({ engine: this.id, from: artifact.id, target: target.id })
      };
    },

    /** 量化(校准集可选)→ quantized-model payload */
    async quantize({ artifact, dataset, scheme }) {
      return {
        kind: 'quantized-model',
        content: JSON.stringify({ engine: this.id, from: artifact.id, dataset: dataset ? dataset.id : undefined, scheme })
      };
    },

    /** 代码生成 → generated-code payload */
    async generateCode({ artifact, config }) {
      return {
        kind: 'generated-code',
        content: `/* generated by ${this.id} | source: ${artifact.id} | outputDir: ${config.outputDir} */\n`
      };
    },

    /** 在目标上运行推理(可选,评测已由 measurement provider 承担) */
    async run({ bundle, target }) {
      return { ok: true, outputs: { label: 'unknown' } };
    }
  };
}

module.exports = { createTemplateEngine };
